### ISSUE TITLE
pod

### ISSUE THREAD

**Issue by ZCLemo** [teddylong/iOSGank#1]
下载后pod不行

**Comment by teddylong** [comment]
pod 没install? 或者没update?

**Comment by ZCLemo** [comment]
pod install 和 update 都不行，难道是我的pod版本问题，我的pod版本1.0.1

**Comment by teddylong** [comment]
我的比较老,可能pod的写法还是之前的,我的是0.39.0

**Comment by teddylong** [comment]
你可以换成新的写法,,,官网查下!

**Comment by williamwue** [comment]
将Podfile修改为
target 'swiftMeiZi' do
pod 'RAMPaperSwitch', '~> 0.0.3'
...
end
